# Generated by Django 3.1 on 2020-08-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio_app/images/')),
                ('url', models.URLField()),
            ],
        ),
    ]
