# Generated by Django 3.1 on 2020-08-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='url',
            new_name='link',
        ),
    ]
